openapi: 3.0.1
info:
  title: CONTRACT Plugin
  description: A plugin that allows the user to create and manage a CONTRACT list using ChatGPT.
  version: "v1"
servers:
  - url: http://localhost:3000
paths:
  /api/contracts:
    get:
      operationId: getContracts
      summary: Get the list of contracts
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getContractsResponse"
  /api/create-contract:
    post:
      operationId: addContract
      summary: add a new contract
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/addContractRequest"
      responses:
        "200":
          description: OK
  /api/delete-contract:
    post:
      operationId: deleteContract
      summary: delete a contract
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/deleteContractRequest"
      responses:
        "200":
          description: OK
  /api/deploy-contract:
    post:
      operationId: deployContract
      summary: deploy a contract
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/deployContractRequest"
      responses:
        "200":
          description: OK
components:
  schemas:
    Contract:
      type: object
      required:
        - address
        - chain
        - sourceCode
      properties:
        address:
          type: string
          description: The address of the contract.
        chain:
          type: string
          description: The blockchain network of the contract.
        sourceCode:
          type: string
          description: The source code of the contract.
        name:
          type: string
          description: The name of the contract.
        compilerVersion:
          type: string
          description: The version of the Solidity compiler used to compile the contract.
    deleteContractRequest:
      type: object
      required:
        - contract
      properties:
        contract:
          $ref: "#/components/schemas/Contract"
    addContractRequest:
      type: object
      required:
        - contract
      properties:
        contract:
          $ref: "#/components/schemas/Contract"
    getContractsResponse:
      type: object
      properties:
        contracts:
          type: array
          items:
            $ref: "#/components/schemas/Contract"
          description: The list of contracts.
    deployContractRequest:
      type: object
      required:
        - chain
        - sourceCode
      properties:
        chain:
          type: string
          description: The blockchain network of the contract.
        sourceCode:
          type: string
          description: The source code of the contract.
        name:
          type: string
          description: The name of the contract.
        compilerVersion:
          type: string
          description: The version of the Solidity compiler used to compile the contract.
