openapi: 3.0.1
info:
  title: WEB3GPT Contract Deployer
  description: A plugin to deploy Solidity smart contracts to any EVM chain.
  version: "v1"
servers:
  - url: http://localhost:3000
paths:
  /api/deploy-contract:
    post:
      operationId: deployContract
      summary: deploy a contract.  Must be Solidity version 0.8.20 or greater.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/deployContractRequest"
      responses:
        "200":
          description: OK
components:
  schemas:
    Contract:
      type: object
      required:
        - name
        - address
        - chain
        - sourceCode
      properties:
        name:
          type: string
          description: The name of the contract.
        address:
          type: string
          description: The address of the contract.
        chain:
          type: string
          description: The blockchain network name of the contract.
        sourceCode:
          type: string
          description: The source code of the contract. Must be Solidity version 0.8.20 or greater.
       constructorArgs:
          type: array
          items:
            oneOf:
              - type: string
              - type: array
                items:
                  type: string
          description: The arguments for the contract's constructor. Can be of any type expressed as a string.
    deployContractRequest:
      type: object
      required:
        - name
        - chains
        - sourceCode
        - constructorArgs
      properties:
        name:
          type: string
          description: The name of the contract.  Only letters no spaces or special characters.
        chains:
          type: array
          items:
            type: string
          description: The blockchain networks to deploy the contract to.  No special characters.
        sourceCode:
          type: string
          description: The source code of the contract. Must be Solidity version 0.8.20 or greater.
         constructorArgs:
          type: array
          items:
            oneOf:
              - type: string
              - type: array
                items:
                  type: string
          description: The arguments for the contract's constructor. Can be of any type expressed as a string.